### ISSUE TITLE
Stubbing method which requires arguments

### ISSUE THREAD

**Issue by olimart** [codeodor/minitest-stub_any_instance#15]
Hi,
I'm getting the following error `wrong number of arguments (given 1, expected 0)` when stubbing a method that requires arguments.

Looks like the gem does not support it. Any recommendation? Thanks

**Comment by codeodor** [comment]
Hi @olimart!

I think maybe the problem is something else. I've added a test case showing it works with methods that have arguments: 

https://github.com/codeodor/minitest-stub_any_instance/blob/master/test/stub_any_instance_test.rb#L87

Is that how it your usage looks?

**Comment by olimart** [comment]
Indeed. It opens up new perceptions (at least for me)
Thanks a lot.

**Comment by codeodor** [comment]
I appreciate you letting me know about the problem! I was kind of shocked we hadn't put any tests showing multiple arguments, so it was helpful in rectifying that problem!
