### ISSUE TITLE
Ruby 3 (Keyword Arguments) Support

### ISSUE THREAD

**Issue by mvastola** [codeodor/minitest-stub_any_instance#16]
Not sure if this is still maintained, but I was wondering what (if any) plans there were to support ruby 3 keyword arguments. 

I'd be more than happy to provide a PR, but I problem I see is that such a patch would most likely require dropping support for older ruby versions, so I wanted to know if this was something you'd be willing to do.

The ways I see of doing it are
a) Adding `ruby2_keywords` to stubbed methods (downsides being that `ruby2_keywords` isn't going to be around forever, and that this would require the [`ruby2_keywords`](https://rubygems.org/gems/ruby2_keywords) gem a shim for ruby versions `[2.0, 2.7)`, and this gem doesn't support `1.9.x`.

b) Simply adding `**kwargs` to the argument lists, with the downside being that there would be no support for versions less than 2.7 (I believe).

**Comment by codeodor** [comment]
Closed by #17 ... except the CI. I am trying to look at another option.
